import {
  Banknote,
  BookOpen,
  Briefcase,
  Building2,
  Factory,
  FileSignature,
  Gavel,
  Globe,
  Heart,
  Leaf,
  Radio,
  Shield,
  Truck,
  Users,
  Wheat,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Categoría temática para clasificar avisos del BORA
 */
export interface Categoria {
  /** Identificador único de la categoría */
  id: string;
  /** Nombre para mostrar */
  nombre: string;
  /** Componente de icono de Lucide */
  icon: LucideIcon;
  /** Clase de Tailwind para el color de fondo */
  color: string;
  /** Clase de Tailwind para el color de fondo claro (hover) */
  colorLight: string;
  /** Etiquetas asociadas a esta categoría */
  etiquetas: string[];
}

/**
 * Categorías temáticas con iconos y etiquetas asociadas
 * Usadas para clasificar y filtrar avisos del Boletín Oficial
 *
 * COBERTURA COMPLETA: Incluye todas las etiquetas de la base de datos
 * Última actualización: Diciembre 2025
 */
export const CATEGORIAS: Categoria[] = [
  {
    id: "empleo",
    nombre: "Empleo y Trabajo",
    icon: Briefcase,
    color: "bg-green-500",
    colorLight: "bg-green-50 hover:bg-green-100",
    etiquetas: [
      "#Empleo",
      "#Salarios",
      "#Sindicatos",
      "#Designaciones",
      "#Renuncias",
      "#Ascensos",
      "#Trabajo",
      "#Jubilaciones",
      "#TrabajoYPrevisiónSocial",
      "#TrabajoYPrevisionSocial",
      "#FormacionLaboral",
      "#TrabajoYRural",
      "Trabajo / Empleo / Relaciones laborales",
      "Trabajo y Seguridad Social",
    ],
  },
  {
    id: "energia",
    nombre: "Energía",
    icon: Zap,
    color: "bg-yellow-500",
    colorLight: "bg-yellow-50 hover:bg-yellow-100",
    etiquetas: [
      "#Electricidad",
      "#TarifasEnergeticas",
      "#Hidrocarburos",
      "#EnergiasRenovables",
      "#EnergiaNuclear",
      "#Energia",
      "#Energía",
      "#Combustibles",
      "#Biocombustibles",
      "#AmbienteYEnergia",
      "#InfraestructuraYEnergia",
      "Energía",
    ],
  },
  {
    id: "salud",
    nombre: "Salud",
    icon: Heart,
    color: "bg-red-500",
    colorLight: "bg-red-50 hover:bg-red-100",
    etiquetas: ["#Salud", "Salud"],
  },
  {
    id: "economia",
    nombre: "Economía y Finanzas",
    icon: Banknote,
    color: "bg-blue-500",
    colorLight: "bg-blue-50 hover:bg-blue-100",
    etiquetas: [
      "#ActividadEconomica",
      "#Finanzas",
      "#Impuestos",
      "#ComercioExterior",
      "#ComercioInterior",
      "#TipoDeCambio",
      "#Presupuesto",
      "#DeudaPublica",
      "#CreditosHipotecarios",
      "#Subsidios",
      "#Coparticipacion",
      "#Inflacion",
      "#AcuerdosComerciales",
      "#Aduana",
      "#Economia",
      "Finanzas públicas / Hacienda",
      "Finanzas Públicas",
      "Economía y Producción",
      "Comercio / Consumo / Defensa del consumidor",
    ],
  },
  {
    id: "justicia",
    nombre: "Justicia y DDHH",
    icon: Gavel,
    color: "bg-purple-500",
    colorLight: "bg-purple-50 hover:bg-purple-100",
    etiquetas: [
      "#Justicia",
      "#DerechosHumanos",
      "Justicia",
      "Justicia y Derechos Humanos",
      "Derechos Humanos",
    ],
  },
  {
    id: "transporte",
    nombre: "Transporte e Infraestructura",
    icon: Truck,
    color: "bg-cyan-500",
    colorLight: "bg-cyan-50 hover:bg-cyan-100",
    etiquetas: [
      "#Transporte",
      "#Vialidad",
      "#ObrasPublicas",
      "#Infraestructura",
      "#InfraestructuraYServiciosPublicos",
      "#InfraestructuraYTransporte",
      "Infraestructura y Transporte",
      "Transporte",
      "Obras públicas",
    ],
  },
  {
    id: "gobierno",
    nombre: "Gobierno y Administración",
    icon: Building2,
    color: "bg-slate-500",
    colorLight: "bg-slate-50 hover:bg-slate-100",
    etiquetas: [
      "#Administración",
      "#Administracion",
      "#BienesDelEstado",
      "#ComprasPublicas",
      "#Transparencia",
      "#Desburocratizacion",
      "#Contratos",
      "#Licitaciones",
      "#Convenios",
      "Administración Pública y Gobierno",
      "Administración pública / Gobernanza",
    ],
  },
  {
    id: "agro",
    nombre: "Agro y Alimentos",
    icon: Wheat,
    color: "bg-amber-500",
    colorLight: "bg-amber-50 hover:bg-amber-100",
    etiquetas: ["#Agroindustria", "Agricultura / Campo / Desarrollo rural"],
  },
  {
    id: "seguridad",
    nombre: "Seguridad y Defensa",
    icon: Shield,
    color: "bg-stone-500",
    colorLight: "bg-stone-50 hover:bg-stone-100",
    etiquetas: [
      "#SeguridadInterior",
      "#Defensa",
      "#Narcotrafico",
      "Seguridad",
      "Defensa / Fuerzas Armadas",
      "Política Exterior y Defensa",
    ],
  },
  {
    id: "industria",
    nombre: "Industria y PyMEs",
    icon: Factory,
    color: "bg-indigo-500",
    colorLight: "bg-indigo-50 hover:bg-indigo-100",
    etiquetas: [
      "#Industria",
      "#PyMEs",
      "#CienciaYTecnica",
      "#EconomiaDelConocimiento",
      "#Mineria",
      "#Litio",
      "#InteligenciaArtificial",
      "Industria",
      "Economía del Conocimiento y Telecomunicaciones",
      "Educación, Ciencia y Tecnología",
    ],
  },
  {
    id: "comunicaciones",
    nombre: "Comunicaciones",
    icon: Radio,
    color: "bg-pink-500",
    colorLight: "bg-pink-50 hover:bg-pink-100",
    etiquetas: [
      "#Comunicaciones",
      "#Conectividad",
      "#ServicioUniversal",
      "Medios / Comunicación",
    ],
  },
  {
    id: "social",
    nombre: "Desarrollo Social",
    icon: Users,
    color: "bg-orange-500",
    colorLight: "bg-orange-50 hover:bg-orange-100",
    etiquetas: [
      "#DesarrolloSocial",
      "#PolíticasDeVivienda",
      "#ViviendaYConstruccion",
      "#Alquileres",
      "#AsistenciaSocial",
      "#ParticipacionCiudadana",
      "Desarrollo social / Inclusión / Pobreza",
      "Desarrollo Social",
      "Vivienda / Urbanismo",
      "Pueblos originarios",
      "Migraciones / Extranjería / Refugio",
    ],
  },
  {
    id: "educacion",
    nombre: "Educación y Cultura",
    icon: BookOpen,
    color: "bg-teal-500",
    colorLight: "bg-teal-50 hover:bg-teal-100",
    etiquetas: [
      "#Educacion",
      "#Cultura",
      "#Deportes",
      "#Turismo",
      "Educación",
      "Cultura",
      "Deporte",
      "Turismo",
      "Cultura y Medios",
    ],
  },
  {
    id: "ambiente",
    nombre: "Ambiente y Recursos",
    icon: Leaf,
    color: "bg-lime-500",
    colorLight: "bg-lime-50 hover:bg-lime-100",
    etiquetas: [
      "#Ambiente",
      "#RecursosHidricos",
      "#Agua",
      "#Saneamiento",
      "#Sustentabilidad",
      "#ParquesNacionales",
      "Ambiente",
      "Ambiente y Recursos Naturales",
    ],
  },
  {
    id: "exterior",
    nombre: "Relaciones Exteriores",
    icon: Globe,
    color: "bg-rose-500",
    colorLight: "bg-rose-50 hover:bg-rose-100",
    etiquetas: [
      "#RelacionesExteriores",
      "#Cancilleria",
      "Relaciones exteriores / Política internacional",
    ],
  },
  {
    id: "otros",
    nombre: "Otros",
    icon: FileSignature,
    color: "bg-gray-500",
    colorLight: "bg-gray-50 hover:bg-gray-100",
    etiquetas: ["#Infracciones", "Elecciones"],
  },
];
